apiVersion: v1
kind: Service
metadata:
  name: github-runners
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: github-runners
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: github-runners
spec:
  image: ghcr.io/santhoshnath/github-runner:ubuntu-22.04
  organization: benzene-tech
  labels:
    - benzene-ubuntu
  serviceName: github-runners
  selector:
    matchLabels:
      app: github-runners
  template:
    metadata:
      labels:
        app: github-runners
    spec:
      containers:
        - name: runner
          securityContext:
            privileged: false
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: github-runners
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleDownDelaySecondsAfterScaleOut: 300
  scaleTargetRef:
    kind: RunnerSet
    name: github-runners
  metrics:
    - type: PercentageRunnersBusy
      scaleUpThreshold: '0.75'
      scaleDownThreshold: '0.25'
      scaleUpFactor: '2'
      scaleDownFactor: '0.5'
