name: Build

on:
  push:
    branches:
      - "master"
    paths:
      - "Dockerfile"
      - "Dockerfile-dind"
      - "Dockerfile-dind-rootless"

concurrency: ${{ github.workflow }}

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push runner images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/santhoshnath/github-runner:ubuntu-22.04

      - name: Build and push DinD runner images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-dind
          push: true
          tags: ghcr.io/santhoshnath/github-runner:ubuntu-20.04-dind

      - name: Build and push DinD rootless runner images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-dind-rootless
          push: true
          tags: ghcr.io/santhoshnath/github-runner:ubuntu-20.04-dind-rootless
